//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natariys.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int id_user { get; set; }
        public string name { get; set; }
    
        public virtual users users { get; set; }
    }
}
